version: '3'
services:
  openresty:
    build: ./openresty
    environment:
        - JWT_SECRET=secret
    ports:
        - "8080:8080"
    volumes:
        - ./openresty/nginx.conf:/nginx.conf
        - ./openresty/bearer.lua:/bearer.lua
    links:
        - redis

  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf